#include "generated/include/GameEngine.h"
using namespace std;

/*
 ACESTA ESTE UN JOC CE VA SIMULA COMENZI DE LINUX PRECUM CD,LS, ETC...
 SCOPUL JUCATORULUI ESTE SA REZOLVE NISTE PUZZLE-URI FOLOSIND METODE REALE DE DECRIPTARE, HASHING ETC...
 FIECARE CLASA ARE SCOPUL EI, AVAND UN NUME SUGESTIV
 EXISTA 3 PERSONALITATI ALE HACKER-ULUI LA CARE JUCATORUL VA AVEA ACCESS - FIECARE CU DIVERSE SPECIALIZARI
 */

int main() {
    GameEngine game("tastatura.txt");
    game.start();
    return 0;
}