name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cppcheck

        uses: ./.github/actions/cppcheck

      - name: Run Clang-Tidy
      
        uses: ./.github/actions/clang-tidy
